name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: Datadog
        uses: kennonkwok/datadog-actions@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          events: |
            - title: "Hello Datadog!"
              text: "Hello from ${{github.ref}}"
              alert_type: "info"
              host: ${{ github.repository_owner }}
              source_type_name: "github"
              tags:
                - "project:${{ github.repository }}"